version: "3.5"

networks:
  app-network:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: api
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SERVER_ADDRESS: api
      SERVER_PORT: 8080
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_URL: jdbc:postgresql://54.226.233.18:5432/beautysalondb?createDatabaseIfNotExist=true
  ui:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    image: ui
    container_name: ui
    restart: always
    ports:
      - "8083:8083"
    networks:
      - app-network
    environment:
      SERVER_ADDRESS: ui
      SERVER_PORT: 8083
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_URL: jdbc:postgresql://54.226.233.18:5432/beautysalondb?createDatabaseIfNotExist=true