server:
  address: localhost
  port: 8083

api:
  base-url: "http://${server.address}:${server.port}/panel"

spring:
  application:
    name: backend-ui
  datasource:
    username: "postgres"
    password: "postgres"
    url: "jdbc:postgresql://localhost:5432/beautysalon_db"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true